### ISSUE TITLE
Mysterious characters not parsing from json

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/pyneurovault#8]
When using the API with urllib2 to read the json into a data structure, there seem to be some kind of invalid characters leading to error:

> > > nv = api.NeuroVault()
> > > Extracting NeuroVault images meta data...
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/vsochat/.local/lib/python2.6/site-packages/pyneurovault-0.1.0-py2.6.egg/pyneurovault/api.py", line 55, in **init**
> > >     self.images = self.get_images()  
> > >   File "/home/vsochat/.local/lib/python2.6/site-packages/pyneurovault-0.1.0-py2.6.egg/pyneurovault/api.py", line 73, in get_images
> > >     images = DataJson("http://neurovault.org/api/images/?format=json")
> > >   File "/home/vsochat/.local/lib/python2.6/site-packages/pyneurovault-0.1.0-py2.6.egg/pyneurovault/utils.py", line 46, in **init**
> > >     self.json = self.**get_json**()
> > >   File "/home/vsochat/.local/lib/python2.6/site-packages/pyneurovault-0.1.0-py2.6.egg/pyneurovault/utils.py", line 55, in **get_json**
> > >     return urllib2.urlopen(self.url).read().encode("utf-8")
> > > UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 21126: ordinal not in range(128)

This needs to be addressed! We don't have much control over what users copy paste / write in their text boxes, so it probably is best to deal with here. We need a solution that is reasonably fast and deals with such characters.

**Comment by vsoch** [comment]
Fixed https://github.com/NeuroVault/pyneurovault/commit/a0b3fb32a206f22f14f72791625ccf220d0e622d#diff-a6caa7af93cdc528ca2769edc8ffd900R56

May still be an issue when saving to file, but API is back to working
